name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: "8.1"
      - uses: php-actions/phpunit@v2
        with:
          php_version: "8.1"
      - uses: php-actions/phpstan@v3
        with:
          php_version: "8.1"
          version: "2.4.0"
