name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: "8.1"
      - uses: php-actions/phpunit@v2
        with:
          php_version: "8.1"
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
      - name: Running Phpstan
        run: ./vendor/bin/phpstan analyse
        with:
          php_version: "8.1"
